# Generated by Django 3.0.8 on 2020-08-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_author', models.CharField(default='Anonymous', max_length=50)),
                ('blog_title', models.CharField(default='', max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('blog_content', models.TextField()),
            ],
        ),
    ]
