# Generated by Django 3.0.8 on 2020-08-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='smug',
            field=models.CharField(default='smug', max_length=20),
            preserve_default=False,
        ),
    ]
